<a href="https://colab.research.google.com/github/Prashanth2957/Movie-Recommender-System-Using-NLP/blob/main/movie_recomendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity



In [5]:
movies_data=pd.read_csv('/content/tmdb_5000_movies.csv')

In [ ]:
movies_data.head()

In [6]:
movies_data.shape

(4803, 20)

In [7]:
# selecting some relavent features for recimmendation
selected_features=['genres','keywords','tagline','cast','director','overview']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director', 'overview']


In [10]:
features_to_fill = [feature for feature in selected_features if feature in movies_data.columns]

for feature in features_to_fill:
  movies_data[feature]=movies_data[feature].fillna('')

In [12]:
present_features = [feature for feature in selected_features if feature in movies_data.columns]
combined_features = movies_data[present_features[0]].astype(str)
for feature in present_features[1:]:
    combined_features = combined_features + ' ' + movies_data[feature].astype(str)

In [13]:
print(combined_features)

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...                        
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801    [] [] A New Yorker in Shanghai When ambitious ...
4802    [{"id": 99, "name": "Documentary"}] [{"id": 15...
Length: 4803, dtype: object


In [14]:
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 329408 stored elements and shape (4803, 33542)>
  Coords	Values
  (0, 20199)	0.37401966585634167
  (0, 7052)	0.03603782751125524
  (0, 24034)	0.37401966585634167
  (0, 10254)	0.03534794254724929
  (0, 668)	0.04113210628113712
  (0, 10371)	0.040564503360523564
  (0, 945)	0.050415928536459306
  (0, 17557)	0.05001644052061316
  (0, 9733)	0.04751299316983126
  (0, 28322)	0.04696787599185187
  (0, 17765)	0.04710229456481479
  (0, 1041)	0.10072524707819938
  (0, 14967)	0.08613047362313951
  (0, 13789)	0.09091564915352443
  (0, 7148)	0.08341752250630552
  (0, 18424)	0.06425420582988291
  (0, 7546)	0.12467373928500694
  (0, 29500)	0.27622834060629875
  (0, 32741)	0.09964129552739377
  (0, 7555)	0.11206591760418239
  (0, 14055)	0.09720777382526347
  (0, 7784)	0.11206591760418239
  (0, 29359)	0.07638515240678383
  (0, 7843)	0.09436486524622945
  (0, 31481)	0.06836486569825767
  :	:
  (4802, 7008)	0.06342211626163982
  (4802, 16289)	0.

In [15]:
similarity=cosine_similarity(feature_vectors)

In [16]:
print(similarity)

[[1.         0.28774145 0.18090301 ... 0.15527507 0.01194801 0.07992733]
 [0.28774145 1.         0.18571951 ... 0.1585299  0.02552384 0.0815891 ]
 [0.18090301 0.18571951 1.         ... 0.10278695 0.01220193 0.05925512]
 ...
 [0.15527507 0.1585299  0.10278695 ... 1.         0.03751729 0.06890388]
 [0.01194801 0.02552384 0.01220193 ... 0.03751729 1.         0.04252539]
 [0.07992733 0.0815891  0.05925512 ... 0.06890388 0.04252539 1.        ]]


In [17]:
similarity.shape

(4803, 4803)

In [18]:
movie_name=input('enter movie name :')

enter movie name :superman


In [19]:
list_of_all_titles=movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [20]:
find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

['Superman', 'Superman II', 'Superman III']


In [21]:
close_match=find_close_match[0]
print(close_match)

Superman


In [23]:
index_of_the_movie = movies_data[movies_data.title == close_match].index[0]
print(index_of_the_movie)

813


In [24]:
similarity_score=list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, np.float64(0.28429558126527843)), (1, np.float64(0.2832609945213526)), (2, np.float64(0.17897611786336512)), (3, np.float64(0.279228935665324)), (4, np.float64(0.2675255665327058)), (5, np.float64(0.27571170720522026)), (6, np.float64(0.17581553589524646)), (7, np.float64(0.2629118667662369)), (8, np.float64(0.21163359085251637)), (9, np.float64(0.34961237531466843)), (10, np.float64(0.5002392859912999)), (11, np.float64(0.13669418011339798)), (12, np.float64(0.2540158944693308)), (13, np.float64(0.16622004803824092)), (14, np.float64(0.4254846061739054)), (15, np.float64(0.18439168965308045)), (16, np.float64(0.2899085456352592)), (17, np.float64(0.23435017585984946)), (18, np.float64(0.14947482672930382)), (19, np.float64(0.15844688252961997)), (20, np.float64(0.21196308213084825)), (21, np.float64(0.14609344637069027)), (22, np.float64(0.1440313620087989)), (23, np.float64(0.1789490699682395)), (24, np.float64(0.19564192925793217)), (25, np.float64(0.17685467440284713)), (26, n

In [25]:
sorted_similarity=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(sorted_similarity)

[(813, np.float64(1.0000000000000002)), (10, np.float64(0.5002392859912999)), (870, np.float64(0.4847283321220485)), (2433, np.float64(0.4432568730785858)), (14, np.float64(0.4254846061739054)), (1296, np.float64(0.42154508768364635)), (119, np.float64(0.3775250728014634)), (2428, np.float64(0.3577872097860124)), (2442, np.float64(0.35070731726091425)), (9, np.float64(0.34961237531466843)), (215, np.float64(0.34836656623332435)), (2217, np.float64(0.34241070603339824)), (123, np.float64(0.3409294316127168)), (165, np.float64(0.3398763141603984)), (64, np.float64(0.3391352527845248)), (65, np.float64(0.33248649968526245)), (232, np.float64(0.32366554547309495)), (196, np.float64(0.3235716494050931)), (4401, np.float64(0.3219399182287647)), (618, np.float64(0.3196975969675925)), (46, np.float64(0.3172364854576183)), (4267, np.float64(0.31659105551394906)), (1720, np.float64(0.31370521473209667)), (4033, np.float64(0.30914939977389777)), (322, np.float64(0.3087149633758922)), (511, np.flo

In [26]:
print("Movies suggested for you :\n")

i=1

for movie in sorted_similarity:
  index = movie[0]
  title_from_index = movies_data.iloc[index]['title']
  if (i<30):
    print(i,'.',title_from_index)
    i+=1

Movies suggested for you :

1 . Superman
2 . Superman Returns
3 . Superman II
4 . Superman IV: The Quest for Peace
5 . Man of Steel
6 . Superman III
7 . Batman Begins
8 . Brooklyn's Finest
9 . Southland Tales
10 . Batman v Superman: Dawn of Justice
11 . Fantastic 4: Rise of the Silver Surfer
12 . Everyone Says I Love You
13 . The Matrix Revolutions
14 . Hulk
15 . X-Men: Apocalypse
16 . The Dark Knight
17 . The Wolverine
18 . Megamind
19 . The Helix... Loaded
20 . Mystery Men
21 . X-Men: Days of Future Past
22 . Batman
23 . Kick-Ass
24 . Super
25 . The Fifth Element
26 . X-Men
27 . Austin Powers: The Spy Who Shagged Me
28 . In the Name of the King: A Dungeon Siege Tale
29 . Mission: Impossible III


In [28]:
movie_name=input('enter movie name :')
list_of_all_titles=movies_data['title'].tolist()

find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
close_match=find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match].index[0]

similarity_score=list(enumerate(similarity[index_of_the_movie]))

sorted_similarity=sorted(similarity_score,key=lambda x:x[1],reverse=True)

print("Movies suggested for you :\n")

i=1

for movie in sorted_similarity:
  index = movie[0]
  title_from_index = movies_data.iloc[index]['title']
  if (i<30):
    print(i,'.',title_from_index)
    i+=1

enter movie name :spyderman
Movies suggested for you :

1 . Superman
2 . Superman Returns
3 . Superman II
4 . Superman IV: The Quest for Peace
5 . Man of Steel
6 . Superman III
7 . Batman Begins
8 . Brooklyn's Finest
9 . Southland Tales
10 . Batman v Superman: Dawn of Justice
11 . Fantastic 4: Rise of the Silver Surfer
12 . Everyone Says I Love You
13 . The Matrix Revolutions
14 . Hulk
15 . X-Men: Apocalypse
16 . The Dark Knight
17 . The Wolverine
18 . Megamind
19 . The Helix... Loaded
20 . Mystery Men
21 . X-Men: Days of Future Past
22 . Batman
23 . Kick-Ass
24 . Super
25 . The Fifth Element
26 . X-Men
27 . Austin Powers: The Spy Who Shagged Me
28 . In the Name of the King: A Dungeon Siege Tale
29 . Mission: Impossible III


In [32]:
import pickle

pickle.dump(movies_data, open('movies.pkl','wb'))
pickle.dump(similarity, open('similarity.pkl','wb'))